//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novartis.Msi.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novartis.Msi.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFilesDesc {
            get {
                return ResourceManager.GetString("AllFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string AllFilesExt {
            get {
                return ResourceManager.GetString("AllFilesExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false color.
        /// </summary>
        internal static string FalseColorPalette {
            get {
                return ResourceManager.GetString("FalseColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grayscale.
        /// </summary>
        internal static string GrayScalePalette {
            get {
                return ResourceManager.GetString("GrayScalePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image (*.jpg).
        /// </summary>
        internal static string JpegFileDescription {
            get {
                return ResourceManager.GetString("JpegFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDataTemplate.xml.
        /// </summary>
        internal static string MetaDataTemplates {
            get {
                return ResourceManager.GetString("MetaDataTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes.xml.
        /// </summary>
        internal static string PalettesFile {
            get {
                return ResourceManager.GetString("PalettesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlugIns.xml.
        /// </summary>
        internal static string PlugInsXmlFile {
            get {
                return ResourceManager.GetString("PlugInsXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image (*.png).
        /// </summary>
        internal static string PngFileDescription {
            get {
                return ResourceManager.GetString("PngFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF Image (*.tiff).
        /// </summary>
        internal static string TiffFileDescription {
            get {
                return ResourceManager.GetString("TiffFileDescription", resourceCulture);
            }
        }
    }
}
