//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novartis.Msi.MSImageView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novartis.Msi.MSImageView.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFilesDesc {
            get {
                return ResourceManager.GetString("AllFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string AllFilesExt {
            get {
                return ResourceManager.GetString("AllFilesExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSImageView.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command line usage.
        /// </summary>
        internal static string CommandLineUsage {
            get {
                return ResourceManager.GetString("CommandLineUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected item(s).
        /// </summary>
        internal static string ConfirmDeleteQuery {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/batch [/saveas [img | imzML]] [/bitmap [jpg | png | tif]] [/outdir path] [/bitmapdir path] [/optwiff] files.
        /// </summary>
        internal static string Switches {
            get {
                return ResourceManager.GetString("Switches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless you specify &apos;/batch&apos; none of the other switches will come to effect.
        ///If you omit all switches, the program will start in interactive mode
        ///and the specified file(s), if any, will be loaded.
        ///If [/outdir path] is given, the results of a conversion (/saveas) or
        ///bitmap creation (/bitmap) will be created in the given directory..
        /// </summary>
        internal static string UsageText {
            get {
                return ResourceManager.GetString("UsageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File (*.xml).
        /// </summary>
        internal static string XmlFileDescription {
            get {
                return ResourceManager.GetString("XmlFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string XmlFileExtension {
            get {
                return ResourceManager.GetString("XmlFileExtension", resourceCulture);
            }
        }
    }
}
